[package]
name = "dust-new"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bevy]
git = "https://github.com/bevyengine/bevy.git"
default-features = false
features = [
    "bevy_winit",
    "x11"
]


[dependencies]
ash = "0.33"
ash-window = "0.7"
gpu-alloc = "0.5.0"
gpu-alloc-ash = "0.2.0"
